#!/bin/bash

# Script para criar o usuário laraveldb e tabela de teste para Laravel
# Execute com: ./create-laravel-user.sh

set -e

# Cores para output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Tentar ler a senha do .env, senão usar padrão
if [ -f .env ]; then
    ORACLE_PWD=$(grep "^ORACLE_PWD=" .env | cut -d'=' -f2 | tr -d '"' | tr -d "'" || echo "Oracle123Secure")
else
    ORACLE_PWD="Oracle123Secure"
fi

LARAVEL_PWD="Oracle123Secure"

echo -e "${BLUE}=========================================="
echo "Criar usuário laraveldb para Laravel"
echo "==========================================${NC}"
echo ""

# Verificar se o container está rodando
if ! docker compose ps | grep -q "oracle19c.*Up"; then
    echo -e "${RED}✗ Container oracle19c não está rodando${NC}"
    echo "   Execute: docker compose up -d"
    exit 1
fi

# Verificar se o Oracle está pronto
CONTAINER_ID=$(docker compose ps -q oracle19c)
HEALTH=$(docker inspect "$CONTAINER_ID" --format='{{.State.Health.Status}}' 2>/dev/null || echo "none")

if [ "$HEALTH" != "healthy" ]; then
    echo -e "${YELLOW}⚠ Oracle ainda não está pronto (Status: $HEALTH)${NC}"
    echo "   Aguarde alguns minutos e execute novamente"
    echo "   Monitore com: docker compose logs -f oracle19c"
    exit 1
fi

echo -e "${GREEN}✓ Oracle está pronto${NC}"
echo ""

# 1. Criar o usuário/schema dentro da PDB ORCLPDB1
echo "1. Criando usuário laraveldb..."
if docker compose exec -T oracle19c sqlplus -s sys/"${ORACLE_PWD}"@localhost:1521/ORCLPDB1 as sysdba <<'SQL' > /dev/null 2>&1
SET PAGESIZE 0 FEEDBACK OFF VERIFY OFF HEADING OFF ECHO OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE
CREATE USER laraveldb IDENTIFIED BY "Oracle123Secure" DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP;
GRANT CONNECT, RESOURCE TO laraveldb;
ALTER USER laraveldb QUOTA UNLIMITED ON USERS;
EXIT;
SQL
then
    echo -e "${GREEN}✓ Usuário laraveldb criado com sucesso${NC}"
else
    # Verificar se o usuário já existe
    USER_EXISTS=$(docker compose exec -T oracle19c sqlplus -s sys/"${ORACLE_PWD}"@localhost:1521/ORCLPDB1 as sysdba <<'SQL' 2>/dev/null | grep -i "laraveldb" || echo "")
SET PAGESIZE 0 FEEDBACK OFF VERIFY OFF HEADING OFF ECHO OFF
SELECT username FROM dba_users WHERE username = 'LARAVELDB';
EXIT;
SQL
)
    if echo "$USER_EXISTS" | grep -qi "laraveldb"; then
        echo -e "${YELLOW}⚠ Usuário laraveldb já existe${NC}"
    else
        echo -e "${RED}✗ Erro ao criar usuário laraveldb${NC}"
        exit 1
    fi
fi

# 2. Conectar como laraveldb e criar a tabela de teste
echo "2. Criando tabela usuarios..."
if docker compose exec -T oracle19c sqlplus -s laraveldb/"${LARAVEL_PWD}"@localhost:1521/ORCLPDB1 <<'SQL' > /dev/null 2>&1
SET PAGESIZE 0 FEEDBACK OFF VERIFY OFF HEADING OFF ECHO OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE
CREATE TABLE usuarios (
    id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nome VARCHAR2(255) NOT NULL,
    CONSTRAINT usuarios_pk PRIMARY KEY (id)
);
EXIT;
SQL
then
    echo -e "${GREEN}✓ Tabela usuarios criada com sucesso${NC}"
else
    # Verificar se a tabela já existe
    TABLE_EXISTS=$(docker compose exec -T oracle19c sqlplus -s laraveldb/"${LARAVEL_PWD}"@localhost:1521/ORCLPDB1 <<'SQL' 2>/dev/null | grep -i "usuarios" || echo "")
SET PAGESIZE 0 FEEDBACK OFF VERIFY OFF HEADING OFF ECHO OFF
SELECT table_name FROM user_tables WHERE table_name = 'USUARIOS';
EXIT;
SQL
)
    if echo "$TABLE_EXISTS" | grep -qi "usuarios"; then
        echo -e "${YELLOW}⚠ Tabela usuarios já existe${NC}"
    else
        echo -e "${RED}✗ Erro ao criar tabela usuarios${NC}"
        exit 1
    fi
fi

# 3. Validação completa do usuário laraveldb
echo "3. Validando usuário laraveldb e objetos criados..."
echo ""

# 3.1. Testar conexão SQL*Plus
echo "   3.1. Testando conexão SQL*Plus..."
SQL_TEST=$(docker compose exec -T oracle19c sqlplus -s laraveldb/"${LARAVEL_PWD}"@localhost:1521/ORCLPDB1 <<'SQL' 2>&1
SET PAGESIZE 0 FEEDBACK OFF VERIFY OFF HEADING OFF ECHO OFF
SELECT 'CONNECTION_OK' FROM DUAL;
EXIT;
SQL
)
if echo "$SQL_TEST" | grep -q "CONNECTION_OK\|Connected"; then
    echo -e "   ${GREEN}✓ Conexão com laraveldb bem-sucedida${NC}"
else
    echo -e "   ${RED}✗ Erro ao conectar com laraveldb${NC}"
    echo "$SQL_TEST"
    exit 1
fi

# 3.2. Verificar se a tabela usuarios existe
echo "   3.2. Verificando tabela usuarios..."
TABLE_COUNT=$(docker compose exec -T oracle19c sqlplus -s laraveldb/"${LARAVEL_PWD}"@localhost:1521/ORCLPDB1 <<'SQL' 2>/dev/null | tr -d ' ' | grep -E "^[0-9]+$" | head -1 || echo "0")
SET PAGESIZE 0 FEEDBACK OFF VERIFY OFF HEADING OFF ECHO OFF
SELECT COUNT(*) FROM user_tables WHERE table_name = 'USUARIOS';
EXIT;
SQL
)
if [ "$TABLE_COUNT" = "1" ]; then
    echo -e "   ${GREEN}✓ Tabela usuarios encontrada${NC}"
else
    echo -e "   ${RED}✗ Tabela usuarios não encontrada (count: $TABLE_COUNT)${NC}"
    exit 1
fi

# 3.3. Verificar estrutura da tabela
echo "   3.3. Verificando estrutura da tabela usuarios..."
TABLE_STRUCTURE=$(docker compose exec -T oracle19c sqlplus -s laraveldb/"${LARAVEL_PWD}"@localhost:1521/ORCLPDB1 <<'SQL' 2>/dev/null
SET PAGESIZE 0 FEEDBACK OFF VERIFY OFF HEADING OFF ECHO OFF
SELECT column_name || ':' || data_type || '(' || data_length || ')'
FROM user_tab_columns
WHERE table_name = 'USUARIOS'
ORDER BY column_id;
EXIT;
SQL
)
if echo "$TABLE_STRUCTURE" | grep -qi "id.*NUMBER\|nome.*VARCHAR2"; then
    echo -e "   ${GREEN}✓ Estrutura da tabela correta${NC}"
    echo "$TABLE_STRUCTURE" | sed 's/^/      /'
else
    echo -e "   ${YELLOW}⚠ Estrutura da tabela pode estar incorreta${NC}"
fi

# 3.4. Verificar constraint de primary key
echo "   3.4. Verificando constraint de primary key..."
PK_EXISTS=$(docker compose exec -T oracle19c sqlplus -s laraveldb/"${LARAVEL_PWD}"@localhost:1521/ORCLPDB1 <<'SQL' 2>/dev/null | grep -i "usuarios_pk" || echo "")
SET PAGESIZE 0 FEEDBACK OFF VERIFY OFF HEADING OFF ECHO OFF
SELECT constraint_name FROM user_constraints WHERE table_name = 'USUARIOS' AND constraint_type = 'P';
EXIT;
SQL
)
if echo "$PK_EXISTS" | grep -qi "usuarios_pk"; then
    echo -e "   ${GREEN}✓ Primary key usuarios_pk encontrada${NC}"
else
    echo -e "   ${YELLOW}⚠ Primary key não encontrada${NC}"
fi

# 3.5. Testar inserção de dados (opcional)
echo "   3.5. Testando inserção de dados..."
INSERT_TEST=$(docker compose exec -T oracle19c sqlplus -s laraveldb/"${LARAVEL_PWD}"@localhost:1521/ORCLPDB1 <<'SQL' 2>&1
SET PAGESIZE 0 FEEDBACK OFF VERIFY OFF HEADING OFF ECHO OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE
INSERT INTO usuarios (nome) VALUES ('Teste');
COMMIT;
SELECT COUNT(*) FROM usuarios WHERE nome = 'Teste';
DELETE FROM usuarios WHERE nome = 'Teste';
COMMIT;
EXIT;
SQL
)
if echo "$INSERT_TEST" | grep -q "1"; then
    echo -e "   ${GREEN}✓ Inserção e exclusão de dados funcionando${NC}"
else
    echo -e "   ${YELLOW}⚠ Teste de inserção falhou ou tabela vazia${NC}"
fi

echo ""
echo -e "${GREEN}=========================================="
echo "✓ Validação completa - Usuário laraveldb pronto!"
echo "==========================================${NC}"
echo ""
echo "📊 Informações de acesso:"
echo "   Usuário: laraveldb"
echo "   Senha: Oracle123Secure"
echo "   Service: ORCLPDB1"
echo "   Host: localhost"
echo "   Port: 1521"
echo ""
echo "📝 Exemplo de conexão JDBC:"
echo "   jdbc:oracle:thin:@localhost:1521/ORCLPDB1"
echo ""
echo "📝 Exemplo de conexão SQL*Plus:"
echo "   docker compose exec oracle19c sqlplus laraveldb/Oracle123Secure@localhost:1521/ORCLPDB1"
echo ""
echo "📝 Para validar novamente:"
echo "   ./validate-oracle.sh"
echo ""

